spring.application.name=prueba
spring.datasource.url=jdbc:h2:mem:test;DATABASE_TO_UPPER=false
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=none
spring.h2.console.enabled=true

security.jwt.expiration-minutes=60
security.jwt.key=OTVlVG9lSXJRSnFWajRGZ3k2VVZ5YW9vcHdwb0thTXFmS3hxR0VWcHNveHR4S2VUT0lxWVl4eXZpYkF6TUZtVA==